### ISSUE TITLE
Se ss

### ISSUE THREAD

**Issue by shaonturaj** [Zlkcyber/pipe-bot#10]
![Screenshot_20241217_131057_Termius](https://github.com/user-attachments/assets/afacc6f7-762a-455c-ba45-f9a66c94c001)

It shows Send heartbeat failed and in earlier issues you said to reg again. So i have tried to reg again now kts showing already exist user. So its not working then i started the script again and it says heartbeat failed. 

![Screenshot_20241217_131232_Termius](https://github.com/user-attachments/assets/2bfce6ef-78ed-4f2f-9354-da6dce20534d)

**Comment by Zlkcyber** [comment]
Delete tokenz.json and relogin using SC option 2

**Comment by youngyeh310** [comment]
![_20241217161741](https://github.com/user-attachments/assets/107302aa-a9c1-4294-bb94-6011be07b6af)
Still the same

**Comment by Zlkcyber** [comment]
Oke will check later

**Comment by shaonturaj** [comment]
Did it but still same error..
