### ISSUE TITLE
I got this , and a cannot run

### ISSUE THREAD

**Issue by mizaty** [Zlkcyber/pipe-bot#3]
[
![Screenshot_20241122-025151](https://github.com/user-attachments/assets/1e29dc32-dc17-4ce3-bab8-2df189ba7361)
]

**Comment by Zlkcyber** [comment]
It's oke just choose what your option 1-3 and enter

**Comment by mizaty** [comment]
Does use multiple proxy will increase more point?

**Comment by Zlkcyber** [comment]
No, it's same

**Comment by mizaty** [comment]
Thanks you
