### ISSUE TITLE
fetch API_BASE url error

### ISSUE THREAD

**Issue by dongsanxiang** [Zlkcyber/pipe-bot#7]
hello sir, i run the project,this error appear.
is the server url changed ? not "https://pipe-network-backend.pipecanary.workers.dev/api"?
![image](https://github.com/user-attachments/assets/8a34eb8a-2f3e-4b7e-877a-7357348aa521)
![image](https://github.com/user-attachments/assets/3d65d209-6560-4cc3-89fb-44a93fc5ef34)

**Comment by Zlkcyber** [comment]
oke updated

**Comment by WP1223** [comment]
what format for accounts.json

**Comment by Zlkcyber** [comment]
@WP1223 just register using random email first, then change to your account after that
