### ISSUE TITLE
error

### ISSUE THREAD

**Issue by maianhbao1** [Zlkcyber/pipe-bot#9]
![Screenshot 2024-12-17 130134](https://github.com/user-attachments/assets/7d50e7a2-8ff5-4275-aed3-bd9a9f59ee76)
what's wrong sir

**Comment by Zlkcyber** [comment]
your account being reset, register again

**Comment by xinzhongyouhai** [comment]
为什么要重新注册啊？

**Comment by maianhbao1** [comment]
> your account being reset, register again

![1](https://github.com/user-attachments/assets/895724c8-8c94-42c0-a348-acb0ff07ef46)
login error sir
